#!/usr/bin/env bash
# This script transfers a file from the client to a server using SCP.

if [ "$#" -ne 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/

if [ $? -eq 0 ]; then
    echo "$1 transferred successfully to $3@$2:~/"
else
    echo "Failed to transfer $1"
fi
