#!/usr/bin/env bash
# This script installs Nginx and configures it to return "Hello World!" on the root path.

# Update package list and install Nginx
sudo apt-get update
sudo apt-get -y install nginx

# Create a simple HTML file with "Hello World!"
echo "Hello World!" > /var/www/html/index.html

# Start the Nginx service
service nginx start
