#!/usr/bin/env bash
# This script configure Nginx for a 301 permanent redirection.

# Define the string for replacement
string_for_replacement="server_name _;\n\trewrite ^/redirect_me https://github.com/lebogangolifant permanent;"

# Use sed to replace the configuration in the Nginx default site file
sudo sed -i "s#server_name _;#$string_for_replacement#" /etc/nginx/sites-enabled/default

# Reload Nginx to apply the configuration changes
sudo service nginx reload
