#!/usr/bin/env bash
# Configure Nginx for a custom 404 page

# Update the package list and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create a custom 404 page with the specified string
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Create a custom Nginx configuration file for the custom error page
custom_config="/etc/nginx/sites-available/custom_404"
sudo tee "$custom_config" > /dev/null <<EOL
server {
    listen 80 default_server;
    server_name _;

    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html;
        internal;
    }

    include /etc/nginx/sites-available/default;
}
EOL

# Create a symbolic link to enable the custom error page configuration
sudo ln -s "$custom_config" /etc/nginx/sites-enabled/

# Test Nginx configuration for syntax errors
sudo nginx -t

# Reload Nginx to apply the configuration changes
sudo service nginx reload
