#!/usr/bin/env bash
# Generate a MySQL dump and creates a compressed archive out of it.

# Get the current day, month, and year as variables.
day=$(date +"%d")
month=$(date +"%m")
year=$(date +"%Y")
# Create a file name for the backup in the format 'day-month-year.tar.gz'.
file_name="$day-$month-$year.tar.gz"
# Use mysqldump to create a MySQL dump of all databases.
mysqldump --all-databases -u root --password="$1" > backup.sql
# Create a tar-gzipped archive of the 'backup.sql' file.
tar -czvf "$file_name" backup.sql
