#!/usr/bin/env bash
# This script displays listening ports along with the PID and program name.

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run with superuser privileges (sudo)." 
   exit 1
fi

netstat -tulnep | tee tmp_output > /dev/null

# Filter the output to show only the lines with 'LISTEN'
grep 'LISTEN' tmp_output

# Remove the temporary file
rm tmp_output
