#!/usr/bin/env bash
# Bash script that configures Nginx to listen on port 80
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo pkill -o nginx
