#!/usr/bin/env bash
# This script is an init script to manage the manage_my_process background process.

case "$1" in
    start)
        ./manage_my_process start
        ;;
    stop)
        ./manage_my_process stop
        ;;
    restart)
        ./manage_my_process restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
