#!/usr/bin/env bash
# This script displays specific information from the /etc/passwd file.

while read -r line; do
    username=$(echo "$line" | cut -d ':' -f 1)
    uid=$(echo "$line" | cut -d ':' -f 3)
    home=$(echo "$line" | cut -d ':' -f 6)
    echo "$username:$uid:$home"
done < /etc/passwd
