#!/usr/bin/env bash
# This script reads and parses the /etc/passwd to display file information

# Read the /etc/passwd file line by line using the while loop and IFS
while IFS=":" read -r username password userid groupid user_info homedir shell; do
    echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell. $userid's place is protected by the passcode $password, more info about the user here: $user_info"
done < /etc/passwd
