#!/usr/bin/env bash
# This script tells a story about the users from the /etc/passwd file.

while IFS=':' read -r username _ gid _ gecos home shell; do
    passcode=$(grep -E "^$username:" /etc/shadow | cut -d ':' -f 2)
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $gid's place is protected by the passcode $passcode, more info about the user here: $gecos"
done < /etc/passwd
