#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code from the Apache log file.

awk '{ ip_code[$1 " " $9]++ } END { for (ic in ip_code) print ip_code[ic], ic }' apache-access.log | sort -nr
