#!/usr/bin/env bash
# This script loops from 1 to 10 and displays different messages based on the loop iteration.

display=1

while ((display <= 10)); do
    if ((display == 4)); then
        echo "bad luck"
    elif ((display == 8)); then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((display++))
done
