#!/usr/bin/env bash
# This script displays numbers from 1 to 20 and specific messages for certain iterations.

display=1

while ((display <= 20)); do
    case $display in
        4)
            echo "$display"
            echo "bad luck from China"
            ;;
        9)
            echo "$display"
            echo "bad luck from Japan"
            ;;
        17)
            echo "$display"
            echo "bad luck from Italy"
            ;;
        *)
            echo "$display"
            ;;
    esac
    ((display++))
done
