#!/usr/bin/env bash
# Configure Nginx to run as the nginx user and listen on all active IPs on port 8080
sed -i 's/Listen 8080/#Listen 8080/g' /etc/apache2/ports.conf
sed -i 's/#user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
pkill apache2
chmod 755 /etc/apache2/ports.conf /etc/nginx/nginx.conf | sudo -u nginx service nginx restart
