#!/usr/bin/env bash
apt-get install -y nginx
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf
printf 'server { listen 8080 default_server; server_name _; location / { return 200 "Hello, Nginx is running as the nginx user!\n"; } }' > /etc/nginx/sites-available/your-config
rm -f /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/your-config /etc/nginx/sites-enabled/
service nginx restart
