#!/usr/bin/env bash
# Bash script that configure Nginx to run as the nginx user and listen on all active IPs on port 8080
pkill apache2
sed -i 's/\s*#?\s*user .*/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
su nginx -c "service nginx start"
